//! PortalToken DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PortalToken;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PortalTokenStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PortalToken
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePortalTokenDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalTokenStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rotated_at")]
    pub rotated_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rotated_to")]
    pub rotated_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_used_at")]
    pub last_used_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PortalToken
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePortalTokenDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalTokenStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rotated_at")]
    pub rotated_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "rotated_to")]
    pub rotated_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_used_at")]
    pub last_used_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PortalToken
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPortalTokenDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_nonce")]
    pub token_nonce: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_expires_at")]
    pub token_expires_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PortalTokenStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rotated_at")]
    pub rotated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "rotated_to")]
    pub rotated_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_used_at")]
    pub last_used_at: Option<DateTime<Utc>>,
}

impl PatchPortalTokenDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.token_nonce.is_some() || self.token_expires_at.is_some() || self.status.is_some() || self.rotated_at.is_some() || self.rotated_to.is_some() || self.revoked_at.is_some() || self.revocation_reason.is_some() || self.last_used_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PortalToken entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalTokenResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalTokenStatus,
    pub rotated_at: Option<DateTime<Utc>>,
    pub rotated_to: Option<Uuid>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PortalToken entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalTokenListResponseDto {
    /// List of items
    pub items: Vec<PortalTokenResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PortalTokenListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PortalTokenResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalTokenSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PortalToken> for PortalTokenResponseDto {
    fn from(entity: PortalToken) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            status: entity.status,
            rotated_at: entity.rotated_at,
            rotated_to: entity.rotated_to,
            revoked_at: entity.revoked_at,
            revocation_reason: entity.revocation_reason,
            last_used_at: entity.last_used_at,
            metadata: entity.metadata,
        }
    }
}

impl From<PortalToken> for PortalTokenSummaryDto {
    fn from(entity: PortalToken) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            created_at,
        }
    }
}

impl From<CreatePortalTokenDto> for PortalToken {
    fn from(dto: CreatePortalTokenDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            token_nonce: dto.token_nonce,
            token_expires_at: dto.token_expires_at,
            status: dto.status,
            rotated_at: dto.rotated_at,
            rotated_to: dto.rotated_to,
            revoked_at: dto.revoked_at,
            revocation_reason: dto.revocation_reason,
            last_used_at: dto.last_used_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PortalToken> for PortalTokenResponseDto {
    fn from(entity: &PortalToken) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            token_nonce: entity.token_nonce.clone(),
            token_expires_at: entity.token_expires_at.clone(),
            status: entity.status.clone(),
            rotated_at: entity.rotated_at.clone(),
            rotated_to: entity.rotated_to.clone(),
            revoked_at: entity.revoked_at.clone(),
            revocation_reason: entity.revocation_reason.clone(),
            last_used_at: entity.last_used_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePortalTokenDto> for PortalToken {
    fn from_create_dto(dto: CreatePortalTokenDto) -> backbone_core::ServiceResult<Self> {
        Ok(PortalToken::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePortalTokenDto> for PortalToken {
    fn apply_update(mut self, dto: UpdatePortalTokenDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.token_nonce = dto.token_nonce;
        self.token_expires_at = dto.token_expires_at;
        self.status = dto.status;
        self.rotated_at = dto.rotated_at;
        self.rotated_to = dto.rotated_to;
        self.revoked_at = dto.revoked_at;
        self.revocation_reason = dto.revocation_reason;
        self.last_used_at = dto.last_used_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PortalToken here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
