//! PortalInvite DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PortalInvite;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PortalInviteStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PortalInvite
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePortalInviteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_email")]
    pub recipient_email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalInviteStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "granted_by")]
    pub granted_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redeemed_by")]
    pub redeemed_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redeemed_at")]
    pub redeemed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PortalInvite
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePortalInviteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_email")]
    pub recipient_email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalInviteStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "granted_by")]
    pub granted_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redeemed_by")]
    pub redeemed_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redeemed_at")]
    pub redeemed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PortalInvite
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPortalInviteDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_email")]
    pub recipient_email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_nonce")]
    pub token_nonce: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_expires_at")]
    pub token_expires_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PortalInviteStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "granted_by")]
    pub granted_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "redeemed_by")]
    pub redeemed_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "redeemed_at")]
    pub redeemed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
}

impl PatchPortalInviteDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.recipient_email.is_some() || self.token_nonce.is_some() || self.token_expires_at.is_some() || self.status.is_some() || self.granted_by.is_some() || self.redeemed_by.is_some() || self.redeemed_at.is_some() || self.revoked_at.is_some() || self.revocation_reason.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PortalInvite entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalInviteResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub recipient_email: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalInviteStatus,
    pub granted_by: Option<Uuid>,
    pub redeemed_by: Option<Uuid>,
    pub redeemed_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PortalInvite entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalInviteListResponseDto {
    /// List of items
    pub items: Vec<PortalInviteResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PortalInviteListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PortalInviteResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalInviteSummaryDto {
    pub id: Uuid,
    pub recipient_email: String,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PortalInvite> for PortalInviteResponseDto {
    fn from(entity: PortalInvite) -> Self {
        Self {
            id: entity.id,
            recipient_email: entity.recipient_email,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            status: entity.status,
            granted_by: entity.granted_by,
            redeemed_by: entity.redeemed_by,
            redeemed_at: entity.redeemed_at,
            revoked_at: entity.revoked_at,
            revocation_reason: entity.revocation_reason,
            metadata: entity.metadata,
        }
    }
}

impl From<PortalInvite> for PortalInviteSummaryDto {
    fn from(entity: PortalInvite) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            recipient_email: entity.recipient_email,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            created_at,
        }
    }
}

impl From<CreatePortalInviteDto> for PortalInvite {
    fn from(dto: CreatePortalInviteDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            recipient_email: dto.recipient_email,
            token_nonce: dto.token_nonce,
            token_expires_at: dto.token_expires_at,
            status: dto.status,
            granted_by: dto.granted_by,
            redeemed_by: dto.redeemed_by,
            redeemed_at: dto.redeemed_at,
            revoked_at: dto.revoked_at,
            revocation_reason: dto.revocation_reason,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PortalInvite> for PortalInviteResponseDto {
    fn from(entity: &PortalInvite) -> Self {
        Self {
            id: entity.id.clone(),
            recipient_email: entity.recipient_email.clone(),
            token_nonce: entity.token_nonce.clone(),
            token_expires_at: entity.token_expires_at.clone(),
            status: entity.status.clone(),
            granted_by: entity.granted_by.clone(),
            redeemed_by: entity.redeemed_by.clone(),
            redeemed_at: entity.redeemed_at.clone(),
            revoked_at: entity.revoked_at.clone(),
            revocation_reason: entity.revocation_reason.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePortalInviteDto> for PortalInvite {
    fn from_create_dto(dto: CreatePortalInviteDto) -> backbone_core::ServiceResult<Self> {
        Ok(PortalInvite::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePortalInviteDto> for PortalInvite {
    fn apply_update(mut self, dto: UpdatePortalInviteDto) -> backbone_core::ServiceResult<Self> {
        self.recipient_email = dto.recipient_email;
        self.token_nonce = dto.token_nonce;
        self.token_expires_at = dto.token_expires_at;
        self.status = dto.status;
        self.granted_by = dto.granted_by;
        self.redeemed_by = dto.redeemed_by;
        self.redeemed_at = dto.redeemed_at;
        self.revoked_at = dto.revoked_at;
        self.revocation_reason = dto.revocation_reason;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PortalInvite here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
