//! PortalSignupPolicy DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PortalSignupPolicy;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PortalSignupPolicy
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePortalSignupPolicyDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub enabled: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "updated_by")]
    pub updated_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PortalSignupPolicy
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePortalSignupPolicyDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub enabled: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "updated_by")]
    pub updated_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PortalSignupPolicy
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPortalSignupPolicyDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "updated_by")]
    pub updated_by: Option<Uuid>,
}

impl PatchPortalSignupPolicyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.enabled.is_some() || self.note.is_some() || self.updated_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PortalSignupPolicy entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalSignupPolicyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub enabled: bool,
    pub note: Option<String>,
    pub updated_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PortalSignupPolicy entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalSignupPolicyListResponseDto {
    /// List of items
    pub items: Vec<PortalSignupPolicyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PortalSignupPolicyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PortalSignupPolicyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalSignupPolicySummaryDto {
    pub id: Uuid,
    pub enabled: bool,
    pub note: Option<String>,
    pub updated_by: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PortalSignupPolicy> for PortalSignupPolicyResponseDto {
    fn from(entity: PortalSignupPolicy) -> Self {
        Self {
            id: entity.id,
            enabled: entity.enabled,
            note: entity.note,
            updated_by: entity.updated_by,
            metadata: entity.metadata,
        }
    }
}

impl From<PortalSignupPolicy> for PortalSignupPolicySummaryDto {
    fn from(entity: PortalSignupPolicy) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            enabled: entity.enabled,
            note: entity.note,
            updated_by: entity.updated_by,
            created_at,
        }
    }
}

impl From<CreatePortalSignupPolicyDto> for PortalSignupPolicy {
    fn from(dto: CreatePortalSignupPolicyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            enabled: dto.enabled,
            note: dto.note,
            updated_by: dto.updated_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PortalSignupPolicy> for PortalSignupPolicyResponseDto {
    fn from(entity: &PortalSignupPolicy) -> Self {
        Self {
            id: entity.id.clone(),
            enabled: entity.enabled.clone(),
            note: entity.note.clone(),
            updated_by: entity.updated_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePortalSignupPolicyDto> for PortalSignupPolicy {
    fn from_create_dto(dto: CreatePortalSignupPolicyDto) -> backbone_core::ServiceResult<Self> {
        Ok(PortalSignupPolicy::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePortalSignupPolicyDto> for PortalSignupPolicy {
    fn apply_update(mut self, dto: UpdatePortalSignupPolicyDto) -> backbone_core::ServiceResult<Self> {
        self.enabled = dto.enabled;
        self.note = dto.note;
        self.updated_by = dto.updated_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PortalSignupPolicy here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
