//! PortalAuditLog DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PortalAuditLog;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PortalAuditEvent;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PortalAuditLog
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePortalAuditLogDto {
    pub event: PortalAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invite_id")]
    pub invite_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "token_id")]
    pub token_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PortalAuditLog
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePortalAuditLogDto {
    pub event: PortalAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invite_id")]
    pub invite_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "token_id")]
    pub token_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PortalAuditLog
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPortalAuditLogDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event: Option<PortalAuditEvent>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "invite_id")]
    pub invite_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_id")]
    pub token_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "occurred_at")]
    pub occurred_at: Option<DateTime<Utc>>,
}

impl PatchPortalAuditLogDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.event.is_some() || self.portal_user_id.is_some() || self.invite_id.is_some() || self.token_id.is_some() || self.actor.is_some() || self.detail.is_some() || self.occurred_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PortalAuditLog entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalAuditLogResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub event: PortalAuditEvent,
    pub portal_user_id: Option<Uuid>,
    pub invite_id: Option<Uuid>,
    pub token_id: Option<Uuid>,
    pub actor: Option<String>,
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PortalAuditLog entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalAuditLogListResponseDto {
    /// List of items
    pub items: Vec<PortalAuditLogResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PortalAuditLogListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PortalAuditLogResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalAuditLogSummaryDto {
    pub id: Uuid,
    pub event: PortalAuditEvent,
    pub portal_user_id: Option<Uuid>,
    pub invite_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PortalAuditLog> for PortalAuditLogResponseDto {
    fn from(entity: PortalAuditLog) -> Self {
        Self {
            id: entity.id,
            event: entity.event,
            portal_user_id: entity.portal_user_id,
            invite_id: entity.invite_id,
            token_id: entity.token_id,
            actor: entity.actor,
            detail: entity.detail,
            occurred_at: entity.occurred_at,
            metadata: entity.metadata,
        }
    }
}

impl From<PortalAuditLog> for PortalAuditLogSummaryDto {
    fn from(entity: PortalAuditLog) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            event: entity.event,
            portal_user_id: entity.portal_user_id,
            invite_id: entity.invite_id,
            created_at,
        }
    }
}

impl From<CreatePortalAuditLogDto> for PortalAuditLog {
    fn from(dto: CreatePortalAuditLogDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            event: dto.event,
            portal_user_id: dto.portal_user_id,
            invite_id: dto.invite_id,
            token_id: dto.token_id,
            actor: dto.actor,
            detail: dto.detail,
            occurred_at: dto.occurred_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PortalAuditLog> for PortalAuditLogResponseDto {
    fn from(entity: &PortalAuditLog) -> Self {
        Self {
            id: entity.id.clone(),
            event: entity.event.clone(),
            portal_user_id: entity.portal_user_id.clone(),
            invite_id: entity.invite_id.clone(),
            token_id: entity.token_id.clone(),
            actor: entity.actor.clone(),
            detail: entity.detail.clone(),
            occurred_at: entity.occurred_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePortalAuditLogDto> for PortalAuditLog {
    fn from_create_dto(dto: CreatePortalAuditLogDto) -> backbone_core::ServiceResult<Self> {
        Ok(PortalAuditLog::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePortalAuditLogDto> for PortalAuditLog {
    fn apply_update(mut self, dto: UpdatePortalAuditLogDto) -> backbone_core::ServiceResult<Self> {
        self.event = dto.event;
        self.portal_user_id = dto.portal_user_id;
        self.invite_id = dto.invite_id;
        self.token_id = dto.token_id;
        self.actor = dto.actor;
        self.detail = dto.detail;
        self.occurred_at = dto.occurred_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PortalAuditLog here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
