//! PortalUser DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PortalUser;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PortalUserStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PortalUser
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePortalUserDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "display_name")]
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub street2: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "state_id")]
    pub state_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 24)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vat: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sapiens_user_id")]
    pub sapiens_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_login_at")]
    pub last_login_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PortalUser
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePortalUserDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "display_name")]
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub street2: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "state_id")]
    pub state_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 24)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vat: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sapiens_user_id")]
    pub sapiens_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_login_at")]
    pub last_login_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PortalUser
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPortalUserDto {
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "display_name")]
    pub display_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PortalUserStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub street2: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "state_id")]
    pub state_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 8)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 24)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vat: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sapiens_user_id")]
    pub sapiens_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "revoked_at")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "revocation_reason")]
    pub revocation_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_login_at")]
    pub last_login_at: Option<DateTime<Utc>>,
}

impl PatchPortalUserDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.email.is_some() || self.display_name.is_some() || self.status.is_some() || self.phone.is_some() || self.street.is_some() || self.street2.is_some() || self.city.is_some() || self.state_id.is_some() || self.country_id.is_some() || self.zip.is_some() || self.vat.is_some() || self.company_name.is_some() || self.sapiens_user_id.is_some() || self.revoked_at.is_some() || self.revocation_reason.is_some() || self.archived_at.is_some() || self.last_login_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PortalUser entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalUserResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    pub phone: Option<String>,
    pub street: Option<String>,
    pub street2: Option<String>,
    pub city: Option<String>,
    pub state_id: Option<String>,
    pub country_id: Option<String>,
    pub zip: Option<String>,
    pub vat: Option<String>,
    pub company_name: Option<String>,
    pub sapiens_user_id: Option<Uuid>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub archived_at: Option<DateTime<Utc>>,
    pub last_login_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PortalUser entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalUserListResponseDto {
    /// List of items
    pub items: Vec<PortalUserResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PortalUserListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PortalUserResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PortalUserSummaryDto {
    pub id: Uuid,
    pub email: String,
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PortalUser> for PortalUserResponseDto {
    fn from(entity: PortalUser) -> Self {
        Self {
            id: entity.id,
            email: entity.email,
            display_name: entity.display_name,
            status: entity.status,
            phone: entity.phone,
            street: entity.street,
            street2: entity.street2,
            city: entity.city,
            state_id: entity.state_id,
            country_id: entity.country_id,
            zip: entity.zip,
            vat: entity.vat,
            company_name: entity.company_name,
            sapiens_user_id: entity.sapiens_user_id,
            revoked_at: entity.revoked_at,
            revocation_reason: entity.revocation_reason,
            archived_at: entity.archived_at,
            last_login_at: entity.last_login_at,
            metadata: entity.metadata,
        }
    }
}

impl From<PortalUser> for PortalUserSummaryDto {
    fn from(entity: PortalUser) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            email: entity.email,
            display_name: entity.display_name,
            status: entity.status,
            created_at,
        }
    }
}

impl From<CreatePortalUserDto> for PortalUser {
    fn from(dto: CreatePortalUserDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            email: dto.email,
            display_name: dto.display_name,
            status: dto.status,
            phone: dto.phone,
            street: dto.street,
            street2: dto.street2,
            city: dto.city,
            state_id: dto.state_id,
            country_id: dto.country_id,
            zip: dto.zip,
            vat: dto.vat,
            company_name: dto.company_name,
            sapiens_user_id: dto.sapiens_user_id,
            revoked_at: dto.revoked_at,
            revocation_reason: dto.revocation_reason,
            archived_at: dto.archived_at,
            last_login_at: dto.last_login_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PortalUser> for PortalUserResponseDto {
    fn from(entity: &PortalUser) -> Self {
        Self {
            id: entity.id.clone(),
            email: entity.email.clone(),
            display_name: entity.display_name.clone(),
            status: entity.status.clone(),
            phone: entity.phone.clone(),
            street: entity.street.clone(),
            street2: entity.street2.clone(),
            city: entity.city.clone(),
            state_id: entity.state_id.clone(),
            country_id: entity.country_id.clone(),
            zip: entity.zip.clone(),
            vat: entity.vat.clone(),
            company_name: entity.company_name.clone(),
            sapiens_user_id: entity.sapiens_user_id.clone(),
            revoked_at: entity.revoked_at.clone(),
            revocation_reason: entity.revocation_reason.clone(),
            archived_at: entity.archived_at.clone(),
            last_login_at: entity.last_login_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePortalUserDto> for PortalUser {
    fn from_create_dto(dto: CreatePortalUserDto) -> backbone_core::ServiceResult<Self> {
        Ok(PortalUser::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePortalUserDto> for PortalUser {
    fn apply_update(mut self, dto: UpdatePortalUserDto) -> backbone_core::ServiceResult<Self> {
        self.email = dto.email;
        self.display_name = dto.display_name;
        self.status = dto.status;
        self.phone = dto.phone;
        self.street = dto.street;
        self.street2 = dto.street2;
        self.city = dto.city;
        self.state_id = dto.state_id;
        self.country_id = dto.country_id;
        self.zip = dto.zip;
        self.vat = dto.vat;
        self.company_name = dto.company_name;
        self.sapiens_user_id = dto.sapiens_user_id;
        self.revoked_at = dto.revoked_at;
        self.revocation_reason = dto.revocation_reason;
        self.archived_at = dto.archived_at;
        self.last_login_at = dto.last_login_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PortalUser here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
