//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod portal_audit_log_specification;
pub mod portal_invite_specification;
pub mod portal_signup_policy_specification;
pub mod portal_token_specification;
pub mod portal_user_specification;

// <<< CUSTOM
// END CUSTOM
