//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod portal_audit_log_service;
pub mod portal_invite_service;
pub mod portal_signup_policy_service;
pub mod portal_token_service;
pub mod portal_user_service;

// <<< CUSTOM
// Hand-written portal services (user-owned files — see
// metaphor.codegen.yaml; NOT GenericCrudService aliases).
pub mod portal_error;
pub mod token_service;
pub mod invite_service;
pub mod policy_service;
pub mod credential_port;
pub mod access_service;
pub mod lifecycle_handler;
pub mod portal_surface;
// END CUSTOM

pub use portal_audit_log_service::PortalAuditLogService;
pub use portal_invite_service::PortalInviteService;
pub use portal_signup_policy_service::PortalSignupPolicyService;
pub use portal_token_service::PortalTokenService;
pub use portal_user_service::PortalUserService;
// <<< CUSTOM
pub use access_service::AccessService;
pub use credential_port::{
    CredentialCheck, CredentialVerifierError, CredentialVerifierSlot, PortalCredentialVerifier,
};
pub use invite_service::InviteService;
pub use lifecycle_handler::SapiensLifecycleHandler;
pub use policy_service::PolicyService;
pub use portal_error::PortalError;
pub use portal_surface::{
    PgPortalSurface, PortalAccessEvent, PortalAccountView, PortalDetailPatch,
    PortalDocumentSurface, WRITABLE_DETAIL_FIELDS,
};
pub use token_service::{
    AttemptBook, BearerRow, ParsedCapability, PortalPrincipal, RecipientCredential, TokenService,
    PORTAL_BEARER_SECRET_ENV, PORTAL_RECIPIENT_SECRET_ENV,
};
// END CUSTOM
