//! Application service for PortalAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `portal_audit_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePortalAuditLogDto, UpdatePortalAuditLogDto};
use crate::domain::entity::PortalAuditLog;
use crate::infrastructure::persistence::PortalAuditLogRepository;

/// Application service for PortalAuditLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `portal_audit_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PortalAuditLogServiceCustom {
///     inner: Arc<PortalAuditLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PortalAuditLogService = GenericCrudService<
    PortalAuditLog,
    CreatePortalAuditLogDto,
    UpdatePortalAuditLogDto,
    PortalAuditLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
