//! Application service for PortalUser entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `portal_user_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePortalUserDto, UpdatePortalUserDto};
use crate::domain::entity::PortalUser;
use crate::infrastructure::persistence::PortalUserRepository;

/// Application service for PortalUser entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `portal_user_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PortalUserServiceCustom {
///     inner: Arc<PortalUserService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PortalUserService = GenericCrudService<
    PortalUser,
    CreatePortalUserDto,
    UpdatePortalUserDto,
    PortalUserRepository,
>;

// <<< CUSTOM
// END CUSTOM
