-- PortalToken Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the portal.portal_tokens table.
-- Customize this file to add your initial data.

-- INSERT INTO portal.portal_tokens (
--     id,
--     user_id,
--     token_nonce,
--     token_expires_at,
--     status,
--     rotated_at,
--     rotated_to,
--     revoked_at,
--     revocation_reason,
--     last_used_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO portal.portal_tokens (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

