-- PortalUser Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the portal.portal_users table.
-- Customize this file to add your initial data.

-- INSERT INTO portal.portal_users (
--     id,
--     email,
--     display_name,
--     status,
--     phone,
--     street,
--     street2,
--     city,
--     state_id,
--     country_id,
--     zip,
--     vat,
--     company_name,
--     sapiens_user_id,
--     revoked_at,
--     revocation_reason,
--     archived_at,
--     last_login_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO portal.portal_users (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

