-- PortalSignupPolicy Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the portal.portal_signup_policies table.
-- Customize this file to add your initial data.

-- INSERT INTO portal.portal_signup_policies (
--     id,
--     enabled,
--     note,
--     updated_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO portal.portal_signup_policies (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

