-- PortalInvite Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the portal.portal_invites table.
-- Customize this file to add your initial data.

-- INSERT INTO portal.portal_invites (
--     id,
--     recipient_email,
--     token_nonce,
--     token_expires_at,
--     status,
--     granted_by,
--     redeemed_by,
--     redeemed_at,
--     revoked_at,
--     revocation_reason,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO portal.portal_invites (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

