-- PortalAuditLog Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the portal.portal_audit_log table.
-- Customize this file to add your initial data.

-- INSERT INTO portal.portal_audit_log (
--     id,
--     event,
--     portal_user_id,
--     invite_id,
--     token_id,
--     actor,
--     detail,
--     occurred_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO portal.portal_audit_log (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

