-- Migration: Create portal_invites table
-- Generated by metaphor-schema

-- Create portal_invite_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_invite_status') THEN
        CREATE TYPE portal_invite_status AS ENUM ('pending', 'redeemed', 'revoked', 'expired');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS portal.portal_invites (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    recipient_email TEXT NOT NULL,
    token_nonce TEXT NOT NULL,
    token_expires_at TIMESTAMPTZ NOT NULL,
    status portal_invite_status NOT NULL DEFAULT 'pending',
    granted_by UUID,
    redeemed_by UUID,
    redeemed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_portal_invites_recipient_email_status ON portal.portal_invites (recipient_email, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_invites_token_nonce ON portal.portal_invites (token_nonce);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_portal_invites_metadata_gin ON portal.portal_invites USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_portal_invites_metadata_deleted_at ON portal.portal_invites ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_portal_invites_metadata_created_at ON portal.portal_invites ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_portal_invites_metadata_updated_at ON portal.portal_invites ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION portal.portal_invites_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_invites_insert_audit ON portal.portal_invites;
CREATE TRIGGER portal_invites_insert_audit BEFORE INSERT ON portal.portal_invites
    FOR EACH ROW EXECUTE FUNCTION portal.portal_invites_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_invites_update_audit ON portal.portal_invites;
CREATE TRIGGER portal_invites_update_audit BEFORE UPDATE ON portal.portal_invites
    FOR EACH ROW EXECUTE FUNCTION portal.portal_invites_audit_timestamp();
