-- Migration: Create portal_signup_policies table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS portal.portal_signup_policies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT,
    updated_by UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_portal_signup_policies_metadata_gin ON portal.portal_signup_policies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_portal_signup_policies_metadata_deleted_at ON portal.portal_signup_policies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_portal_signup_policies_metadata_created_at ON portal.portal_signup_policies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_portal_signup_policies_metadata_updated_at ON portal.portal_signup_policies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION portal.portal_signup_policies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_signup_policies_insert_audit ON portal.portal_signup_policies;
CREATE TRIGGER portal_signup_policies_insert_audit BEFORE INSERT ON portal.portal_signup_policies
    FOR EACH ROW EXECUTE FUNCTION portal.portal_signup_policies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_signup_policies_update_audit ON portal.portal_signup_policies;
CREATE TRIGGER portal_signup_policies_update_audit BEFORE UPDATE ON portal.portal_signup_policies
    FOR EACH ROW EXECUTE FUNCTION portal.portal_signup_policies_audit_timestamp();
