-- Migration: Create portal_tokens table
-- Generated by metaphor-schema

-- Create portal_token_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_token_status') THEN
        CREATE TYPE portal_token_status AS ENUM ('active', 'rotated', 'revoked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS portal.portal_tokens (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    token_nonce TEXT NOT NULL,
    token_expires_at TIMESTAMPTZ NOT NULL,
    status portal_token_status NOT NULL DEFAULT 'active',
    rotated_at TIMESTAMPTZ,
    rotated_to UUID,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    last_used_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_tokens_token_nonce ON portal.portal_tokens (token_nonce);

CREATE INDEX IF NOT EXISTS idx_portal_tokens_user_id_status ON portal.portal_tokens (user_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_portal_tokens_metadata_gin ON portal.portal_tokens USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_portal_tokens_metadata_deleted_at ON portal.portal_tokens ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_portal_tokens_metadata_created_at ON portal.portal_tokens ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_portal_tokens_metadata_updated_at ON portal.portal_tokens ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION portal.portal_tokens_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_tokens_insert_audit ON portal.portal_tokens;
CREATE TRIGGER portal_tokens_insert_audit BEFORE INSERT ON portal.portal_tokens
    FOR EACH ROW EXECUTE FUNCTION portal.portal_tokens_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_tokens_update_audit ON portal.portal_tokens;
CREATE TRIGGER portal_tokens_update_audit BEFORE UPDATE ON portal.portal_tokens
    FOR EACH ROW EXECUTE FUNCTION portal.portal_tokens_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE portal.portal_tokens ADD CONSTRAINT fk_portal_tokens_user_id FOREIGN KEY (user_id) REFERENCES portal.portal_users (id) ON DELETE CASCADE;
