-- Enum types for portal module
-- Generated by metaphor-schema

-- Create portal_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_audit_event') THEN
        CREATE TYPE portal_audit_event AS ENUM ('invite_minted', 'invite_revoked', 'invite_redeemed', 'signup_refused_policy_closed', 'signup_created', 'policy_changed', 'bearer_minted', 'bearer_rotated', 'bearer_revoked', 'recipient_hmac_minted', 'login_succeeded', 'login_refused', 'lifecycle_access_revoked', 'onboarding_linked', 'onboarding_no_invitation', 'credential_port_not_composed');
    END IF;
END
$$;

-- Create portal_invite_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_invite_status') THEN
        CREATE TYPE portal_invite_status AS ENUM ('pending', 'redeemed', 'revoked', 'expired');
    END IF;
END
$$;

-- Create portal_token_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_token_status') THEN
        CREATE TYPE portal_token_status AS ENUM ('active', 'rotated', 'revoked');
    END IF;
END
$$;

-- Create portal_user_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_user_status') THEN
        CREATE TYPE portal_user_status AS ENUM ('invited', 'active', 'revoked', 'archived');
    END IF;
END
$$;

