-- Migration: Create portal_users table
-- Generated by metaphor-schema

-- Create portal_user_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_user_status') THEN
        CREATE TYPE portal_user_status AS ENUM ('invited', 'active', 'revoked', 'archived');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS portal.portal_users (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    display_name TEXT,
    status portal_user_status NOT NULL DEFAULT 'invited',
    phone TEXT,
    street TEXT,
    street2 TEXT,
    city TEXT,
    state_id TEXT,
    country_id TEXT,
    zip TEXT,
    vat TEXT,
    company_name TEXT,
    sapiens_user_id UUID,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    archived_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_portal_users_status ON portal.portal_users (status);

CREATE INDEX IF NOT EXISTS idx_portal_users_sapiens_user_id ON portal.portal_users (sapiens_user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_portal_users_metadata_gin ON portal.portal_users USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_portal_users_metadata_deleted_at ON portal.portal_users ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_portal_users_metadata_created_at ON portal.portal_users ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_portal_users_metadata_updated_at ON portal.portal_users ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION portal.portal_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_users_insert_audit ON portal.portal_users;
CREATE TRIGGER portal_users_insert_audit BEFORE INSERT ON portal.portal_users
    FOR EACH ROW EXECUTE FUNCTION portal.portal_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_users_update_audit ON portal.portal_users;
CREATE TRIGGER portal_users_update_audit BEFORE UPDATE ON portal.portal_users
    FOR EACH ROW EXECUTE FUNCTION portal.portal_users_audit_timestamp();
