-- Audit Triggers Migration for portal module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: PortalAuditLog (portal.portal_audit_log)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION portal.portal_audit_log_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_audit_log_insert_audit ON portal.portal_audit_log;
CREATE TRIGGER portal_audit_log_insert_audit BEFORE INSERT ON portal.portal_audit_log
    FOR EACH ROW EXECUTE FUNCTION portal.portal_audit_log_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_audit_log_update_audit ON portal.portal_audit_log;
CREATE TRIGGER portal_audit_log_update_audit BEFORE UPDATE ON portal.portal_audit_log
    FOR EACH ROW EXECUTE FUNCTION portal.portal_audit_log_audit_timestamp();

-- ==============================================================================
-- Table: PortalInvite (portal.portal_invites)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION portal.portal_invites_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_invites_insert_audit ON portal.portal_invites;
CREATE TRIGGER portal_invites_insert_audit BEFORE INSERT ON portal.portal_invites
    FOR EACH ROW EXECUTE FUNCTION portal.portal_invites_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_invites_update_audit ON portal.portal_invites;
CREATE TRIGGER portal_invites_update_audit BEFORE UPDATE ON portal.portal_invites
    FOR EACH ROW EXECUTE FUNCTION portal.portal_invites_audit_timestamp();

-- ==============================================================================
-- Table: PortalSignupPolicy (portal.portal_signup_policies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION portal.portal_signup_policies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_signup_policies_insert_audit ON portal.portal_signup_policies;
CREATE TRIGGER portal_signup_policies_insert_audit BEFORE INSERT ON portal.portal_signup_policies
    FOR EACH ROW EXECUTE FUNCTION portal.portal_signup_policies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_signup_policies_update_audit ON portal.portal_signup_policies;
CREATE TRIGGER portal_signup_policies_update_audit BEFORE UPDATE ON portal.portal_signup_policies
    FOR EACH ROW EXECUTE FUNCTION portal.portal_signup_policies_audit_timestamp();

-- ==============================================================================
-- Table: PortalToken (portal.portal_tokens)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION portal.portal_tokens_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_tokens_insert_audit ON portal.portal_tokens;
CREATE TRIGGER portal_tokens_insert_audit BEFORE INSERT ON portal.portal_tokens
    FOR EACH ROW EXECUTE FUNCTION portal.portal_tokens_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_tokens_update_audit ON portal.portal_tokens;
CREATE TRIGGER portal_tokens_update_audit BEFORE UPDATE ON portal.portal_tokens
    FOR EACH ROW EXECUTE FUNCTION portal.portal_tokens_audit_timestamp();

-- ==============================================================================
-- Table: PortalUser (portal.portal_users)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION portal.portal_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_users_insert_audit ON portal.portal_users;
CREATE TRIGGER portal_users_insert_audit BEFORE INSERT ON portal.portal_users
    FOR EACH ROW EXECUTE FUNCTION portal.portal_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_users_update_audit ON portal.portal_users;
CREATE TRIGGER portal_users_update_audit BEFORE UPDATE ON portal.portal_users
    FOR EACH ROW EXECUTE FUNCTION portal.portal_users_audit_timestamp();

