-- Migration: Create portal_audit_log table
-- Generated by metaphor-schema

-- Create portal_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portal_audit_event') THEN
        CREATE TYPE portal_audit_event AS ENUM ('invite_minted', 'invite_revoked', 'invite_redeemed', 'signup_refused_policy_closed', 'signup_created', 'policy_changed', 'bearer_minted', 'bearer_rotated', 'bearer_revoked', 'recipient_hmac_minted', 'login_succeeded', 'login_refused', 'lifecycle_access_revoked', 'onboarding_linked', 'onboarding_no_invitation', 'credential_port_not_composed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS portal.portal_audit_log (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event portal_audit_event NOT NULL,
    portal_user_id UUID,
    invite_id UUID,
    token_id UUID,
    actor TEXT,
    detail JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_portal_audit_log_portal_user_id_event ON portal.portal_audit_log (portal_user_id, event);

CREATE INDEX IF NOT EXISTS idx_portal_audit_log_event_occurred_at ON portal.portal_audit_log (event, occurred_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_portal_audit_log_metadata_gin ON portal.portal_audit_log USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_portal_audit_log_metadata_deleted_at ON portal.portal_audit_log ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_portal_audit_log_metadata_created_at ON portal.portal_audit_log ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_portal_audit_log_metadata_updated_at ON portal.portal_audit_log ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION portal.portal_audit_log_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS portal_audit_log_insert_audit ON portal.portal_audit_log;
CREATE TRIGGER portal_audit_log_insert_audit BEFORE INSERT ON portal.portal_audit_log
    FOR EACH ROW EXECUTE FUNCTION portal.portal_audit_log_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS portal_audit_log_update_audit ON portal.portal_audit_log;
CREATE TRIGGER portal_audit_log_update_audit BEFORE UPDATE ON portal.portal_audit_log
    FOR EACH ROW EXECUTE FUNCTION portal.portal_audit_log_audit_timestamp();
