//! Event handler trait for PortalSignupPolicy events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PortalSignupPolicyEvent;

/// Event handler for PortalSignupPolicy events.
/// Implement this trait to react to PortalSignupPolicy lifecycle events.
pub trait PortalSignupPolicyEventHandler: EventHandler<PortalSignupPolicyEvent> {}
