//! Domain events for PortalSignupPolicy entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PortalSignupPolicy;

/// Domain events for PortalSignupPolicy — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PortalSignupPolicy>)` variant.
pub type PortalSignupPolicyEvent = CrudEvent<PortalSignupPolicy>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PortalSignupPolicy events.
pub type PortalSignupPolicyEventPublisher = Arc<dyn CrudEventPublisher<PortalSignupPolicy> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPortalSignupPolicyEventPublisher = NoOpCrudEventPublisher<PortalSignupPolicy>;
