//! Domain events for PortalToken entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PortalToken;

/// Domain events for PortalToken — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PortalToken>)` variant.
pub type PortalTokenEvent = CrudEvent<PortalToken>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PortalToken events.
pub type PortalTokenEventPublisher = Arc<dyn CrudEventPublisher<PortalToken> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPortalTokenEventPublisher = NoOpCrudEventPublisher<PortalToken>;
