//! Event handler trait for PortalUser events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PortalUserEvent;

/// Event handler for PortalUser events.
/// Implement this trait to react to PortalUser lifecycle events.
pub trait PortalUserEventHandler: EventHandler<PortalUserEvent> {}
