//! Domain events for PortalInvite entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PortalInvite;

/// Domain events for PortalInvite — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PortalInvite>)` variant.
pub type PortalInviteEvent = CrudEvent<PortalInvite>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PortalInvite events.
pub type PortalInviteEventPublisher = Arc<dyn CrudEventPublisher<PortalInvite> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPortalInviteEventPublisher = NoOpCrudEventPublisher<PortalInvite>;
