//! Event handler trait for PortalToken events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PortalTokenEvent;

/// Event handler for PortalToken events.
/// Implement this trait to react to PortalToken lifecycle events.
pub trait PortalTokenEventHandler: EventHandler<PortalTokenEvent> {}
