//! Event handler trait for PortalInvite events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PortalInviteEvent;

/// Event handler for PortalInvite events.
/// Implement this trait to react to PortalInvite lifecycle events.
pub trait PortalInviteEventHandler: EventHandler<PortalInviteEvent> {}
