//! Domain events for PortalUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PortalUser;

/// Domain events for PortalUser — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PortalUser>)` variant.
pub type PortalUserEvent = CrudEvent<PortalUser>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PortalUser events.
pub type PortalUserEventPublisher = Arc<dyn CrudEventPublisher<PortalUser> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPortalUserEventPublisher = NoOpCrudEventPublisher<PortalUser>;
