//! Domain events for PortalAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PortalAuditLog;

/// Domain events for PortalAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PortalAuditLog>)` variant.
pub type PortalAuditLogEvent = CrudEvent<PortalAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PortalAuditLog events.
pub type PortalAuditLogEventPublisher = Arc<dyn CrudEventPublisher<PortalAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPortalAuditLogEventPublisher = NoOpCrudEventPublisher<PortalAuditLog>;
