//! PortalSignupPolicy seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PortalSignupPolicy data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PORTALSIGNUPPOLICY SEEDER
// ============================================================================

/// Seeder for portal_signup_policy
pub struct SeedPortalSignupPolicySeeder;

impl SeedPortalSignupPolicySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPortalSignupPolicySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPortalSignupPolicySeeder {
    fn name(&self) -> &'static str {
        "SeedPortalSignupPolicySeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if portal.portal_signup_policies table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM portal.portal_signup_policies")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/portal_signup_policy_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM portal.portal_signup_policies")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
