//! PortalAuditLog seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PortalAuditLog data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PORTALAUDITLOG SEEDER
// ============================================================================

/// Seeder for portal_audit_log
pub struct SeedPortalAuditLogSeeder;

impl SeedPortalAuditLogSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPortalAuditLogSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPortalAuditLogSeeder {
    fn name(&self) -> &'static str {
        "SeedPortalAuditLogSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if portal.portal_audit_log table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM portal.portal_audit_log")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/portal_audit_log_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM portal.portal_audit_log")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
