//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod portal_audit_log_repository;
pub mod portal_invite_repository;
pub mod portal_signup_policy_repository;
pub mod portal_token_repository;
pub mod portal_user_repository;

// Re-exports
pub use portal_audit_log_repository::{
    PortalAuditLogRepository,
    PortalAuditLogPaginationParams,
    PortalAuditLogPaginatedResult,
    PortalAuditLogFilter,
};
pub use portal_invite_repository::{
    PortalInviteRepository,
    PortalInvitePaginationParams,
    PortalInvitePaginatedResult,
    PortalInviteFilter,
};
pub use portal_signup_policy_repository::{
    PortalSignupPolicyRepository,
    PortalSignupPolicyPaginationParams,
    PortalSignupPolicyPaginatedResult,
    PortalSignupPolicyFilter,
};
pub use portal_token_repository::{
    PortalTokenRepository,
    PortalTokenPaginationParams,
    PortalTokenPaginatedResult,
    PortalTokenFilter,
};
pub use portal_user_repository::{
    PortalUserRepository,
    PortalUserPaginationParams,
    PortalUserPaginatedResult,
    PortalUserFilter,
};
