//! Repository trait for PortalToken aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PortalToken aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PortalToken, PortalTokenStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalTokenPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PortalTokenPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PortalTokenPaginatedResult {
    pub data: Vec<PortalToken>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalTokenFilter {
    pub user_id: Option<Uuid>,
    pub token_nonce: Option<String>,
    pub status: Option<PortalTokenStatus>,
    pub rotated_to: Option<Uuid>,
    pub revocation_reason: Option<String>,
}

impl PortalTokenFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.token_nonce.is_some() || self.status.is_some() || self.rotated_to.is_some() || self.revocation_reason.is_some()
    }
}

/// Repository trait for PortalToken aggregate
///
/// This trait defines the persistence contract for PortalToken entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PortalTokenRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new portal_token entity
    async fn save(&self, entity: &PortalToken) -> Result<PortalToken>;

    /// Find portal_token by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PortalToken>>;

    /// Find all portal_token entities
    async fn find_all(&self) -> Result<Vec<PortalToken>>;

    /// Update portal_token by ID
    async fn update(&self, id: &str, entity: &PortalToken) -> Result<Option<PortalToken>>;

    /// Delete portal_token by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List portal_token with pagination
    async fn list(&self, params: PortalTokenPaginationParams) -> Result<PortalTokenPaginatedResult>;

    /// List portal_token with pagination and filters
    async fn list_with_filters(&self, params: PortalTokenPaginationParams, filters: PortalTokenFilter) -> Result<PortalTokenPaginatedResult>;

    /// Count all portal_token entities
    async fn count(&self) -> Result<u64>;

    /// Count portal_token entities matching filters
    async fn count_with_filters(&self, filters: PortalTokenFilter) -> Result<u64>;

    /// Check if portal_token exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete portal_token by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted portal_token by ID
    async fn restore(&self, id: &str) -> Result<Option<PortalToken>>;

    /// List soft-deleted portal_token entities
    async fn list_deleted(&self, params: PortalTokenPaginationParams) -> Result<PortalTokenPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save portal_token entities
    async fn bulk_save(&self, entities: &[PortalToken]) -> Result<Vec<PortalToken>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
