//! Repository trait for PortalSignupPolicy aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PortalSignupPolicy aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::PortalSignupPolicy;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalSignupPolicyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PortalSignupPolicyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PortalSignupPolicyPaginatedResult {
    pub data: Vec<PortalSignupPolicy>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalSignupPolicyFilter {
    pub enabled: Option<bool>,
    pub note: Option<String>,
}

impl PortalSignupPolicyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.enabled.is_some() || self.note.is_some()
    }
}

/// Repository trait for PortalSignupPolicy aggregate
///
/// This trait defines the persistence contract for PortalSignupPolicy entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PortalSignupPolicyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new portal_signup_policy entity
    async fn save(&self, entity: &PortalSignupPolicy) -> Result<PortalSignupPolicy>;

    /// Find portal_signup_policy by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PortalSignupPolicy>>;

    /// Find all portal_signup_policy entities
    async fn find_all(&self) -> Result<Vec<PortalSignupPolicy>>;

    /// Update portal_signup_policy by ID
    async fn update(&self, id: &str, entity: &PortalSignupPolicy) -> Result<Option<PortalSignupPolicy>>;

    /// Delete portal_signup_policy by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List portal_signup_policy with pagination
    async fn list(&self, params: PortalSignupPolicyPaginationParams) -> Result<PortalSignupPolicyPaginatedResult>;

    /// List portal_signup_policy with pagination and filters
    async fn list_with_filters(&self, params: PortalSignupPolicyPaginationParams, filters: PortalSignupPolicyFilter) -> Result<PortalSignupPolicyPaginatedResult>;

    /// Count all portal_signup_policy entities
    async fn count(&self) -> Result<u64>;

    /// Count portal_signup_policy entities matching filters
    async fn count_with_filters(&self, filters: PortalSignupPolicyFilter) -> Result<u64>;

    /// Check if portal_signup_policy exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete portal_signup_policy by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted portal_signup_policy by ID
    async fn restore(&self, id: &str) -> Result<Option<PortalSignupPolicy>>;

    /// List soft-deleted portal_signup_policy entities
    async fn list_deleted(&self, params: PortalSignupPolicyPaginationParams) -> Result<PortalSignupPolicyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save portal_signup_policy entities
    async fn bulk_save(&self, entities: &[PortalSignupPolicy]) -> Result<Vec<PortalSignupPolicy>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
