//! Repository trait for PortalAuditLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PortalAuditLog aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PortalAuditLog, PortalAuditEvent};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalAuditLogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PortalAuditLogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PortalAuditLogPaginatedResult {
    pub data: Vec<PortalAuditLog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalAuditLogFilter {
    pub event: Option<PortalAuditEvent>,
    pub portal_user_id: Option<Uuid>,
    pub invite_id: Option<Uuid>,
    pub token_id: Option<Uuid>,
    pub actor: Option<String>,
}

impl PortalAuditLogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event.is_some() || self.portal_user_id.is_some() || self.invite_id.is_some() || self.token_id.is_some() || self.actor.is_some()
    }
}

/// Repository trait for PortalAuditLog aggregate
///
/// This trait defines the persistence contract for PortalAuditLog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PortalAuditLogRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new portal_audit_log entity
    async fn save(&self, entity: &PortalAuditLog) -> Result<PortalAuditLog>;

    /// Find portal_audit_log by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PortalAuditLog>>;

    /// Find all portal_audit_log entities
    async fn find_all(&self) -> Result<Vec<PortalAuditLog>>;

    /// Update portal_audit_log by ID
    async fn update(&self, id: &str, entity: &PortalAuditLog) -> Result<Option<PortalAuditLog>>;

    /// Delete portal_audit_log by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List portal_audit_log with pagination
    async fn list(&self, params: PortalAuditLogPaginationParams) -> Result<PortalAuditLogPaginatedResult>;

    /// List portal_audit_log with pagination and filters
    async fn list_with_filters(&self, params: PortalAuditLogPaginationParams, filters: PortalAuditLogFilter) -> Result<PortalAuditLogPaginatedResult>;

    /// Count all portal_audit_log entities
    async fn count(&self) -> Result<u64>;

    /// Count portal_audit_log entities matching filters
    async fn count_with_filters(&self, filters: PortalAuditLogFilter) -> Result<u64>;

    /// Check if portal_audit_log exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete portal_audit_log by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted portal_audit_log by ID
    async fn restore(&self, id: &str) -> Result<Option<PortalAuditLog>>;

    /// List soft-deleted portal_audit_log entities
    async fn list_deleted(&self, params: PortalAuditLogPaginationParams) -> Result<PortalAuditLogPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save portal_audit_log entities
    async fn bulk_save(&self, entities: &[PortalAuditLog]) -> Result<Vec<PortalAuditLog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
