//! Repository trait for PortalUser aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PortalUser aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PortalUser, PortalUserStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalUserPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PortalUserPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PortalUserPaginatedResult {
    pub data: Vec<PortalUser>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PortalUserFilter {
    pub email: Option<String>,
    pub display_name: Option<String>,
    pub status: Option<PortalUserStatus>,
    pub phone: Option<String>,
    pub street: Option<String>,
    pub street2: Option<String>,
    pub city: Option<String>,
    pub state_id: Option<String>,
    pub country_id: Option<String>,
    pub zip: Option<String>,
    pub vat: Option<String>,
    pub company_name: Option<String>,
    pub sapiens_user_id: Option<Uuid>,
    pub revocation_reason: Option<String>,
}

impl PortalUserFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.email.is_some() || self.display_name.is_some() || self.status.is_some() || self.phone.is_some() || self.street.is_some() || self.street2.is_some() || self.city.is_some() || self.state_id.is_some() || self.country_id.is_some() || self.zip.is_some() || self.vat.is_some() || self.company_name.is_some() || self.sapiens_user_id.is_some() || self.revocation_reason.is_some()
    }
}

/// Repository trait for PortalUser aggregate
///
/// This trait defines the persistence contract for PortalUser entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PortalUserRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new portal_user entity
    async fn save(&self, entity: &PortalUser) -> Result<PortalUser>;

    /// Find portal_user by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PortalUser>>;

    /// Find all portal_user entities
    async fn find_all(&self) -> Result<Vec<PortalUser>>;

    /// Update portal_user by ID
    async fn update(&self, id: &str, entity: &PortalUser) -> Result<Option<PortalUser>>;

    /// Delete portal_user by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List portal_user with pagination
    async fn list(&self, params: PortalUserPaginationParams) -> Result<PortalUserPaginatedResult>;

    /// List portal_user with pagination and filters
    async fn list_with_filters(&self, params: PortalUserPaginationParams, filters: PortalUserFilter) -> Result<PortalUserPaginatedResult>;

    /// Count all portal_user entities
    async fn count(&self) -> Result<u64>;

    /// Count portal_user entities matching filters
    async fn count_with_filters(&self, filters: PortalUserFilter) -> Result<u64>;

    /// Check if portal_user exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete portal_user by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted portal_user by ID
    async fn restore(&self, id: &str) -> Result<Option<PortalUser>>;

    /// List soft-deleted portal_user entities
    async fn list_deleted(&self, params: PortalUserPaginationParams) -> Result<PortalUserPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save portal_user entities
    async fn bulk_save(&self, entities: &[PortalUser]) -> Result<Vec<PortalUser>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
