//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod portal_audit_log_repository;
mod portal_invite_repository;
mod portal_signup_policy_repository;
mod portal_token_repository;
mod portal_user_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use portal_audit_log_repository::PortalAuditLogRepository;
pub use portal_invite_repository::PortalInviteRepository;
pub use portal_signup_policy_repository::PortalSignupPolicyRepository;
pub use portal_token_repository::PortalTokenRepository;
pub use portal_user_repository::PortalUserRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
