//! Repository for PortalInvite entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PortalInvite, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PortalInvite;

/// Table name for PortalInvite entities
pub const TABLE_NAME: &str = "portal.portal_invites";

/// Repository for PortalInvite entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PortalInviteRepository(
    backbone_orm::GenericCrudRepository<PortalInvite, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PortalInviteRepository {
    type Target = backbone_orm::GenericCrudRepository<PortalInvite, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PortalInviteRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PortalInviteRepository, PortalInvite, soft_delete);
