//! Repository for PortalAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PortalAuditLog, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PortalAuditLog;

/// Table name for PortalAuditLog entities
pub const TABLE_NAME: &str = "portal.portal_audit_log";

/// Repository for PortalAuditLog entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PortalAuditLogRepository(
    backbone_orm::GenericCrudRepository<PortalAuditLog, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PortalAuditLogRepository {
    type Target = backbone_orm::GenericCrudRepository<PortalAuditLog, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PortalAuditLogRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PortalAuditLogRepository, PortalAuditLog, soft_delete);
