//! Repository for PortalUser entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PortalUser, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PortalUser;

/// Table name for PortalUser entities
pub const TABLE_NAME: &str = "portal.portal_users";

/// Repository for PortalUser entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PortalUserRepository(
    backbone_orm::GenericCrudRepository<PortalUser, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PortalUserRepository {
    type Target = backbone_orm::GenericCrudRepository<PortalUser, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PortalUserRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PortalUserRepository, PortalUser, soft_delete);
