//! Repository for PortalSignupPolicy entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PortalSignupPolicy, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PortalSignupPolicy;

/// Table name for PortalSignupPolicy entities
pub const TABLE_NAME: &str = "portal.portal_signup_policies";

/// Repository for PortalSignupPolicy entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PortalSignupPolicyRepository(
    backbone_orm::GenericCrudRepository<PortalSignupPolicy, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PortalSignupPolicyRepository {
    type Target = backbone_orm::GenericCrudRepository<PortalSignupPolicy, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PortalSignupPolicyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PortalSignupPolicyRepository, PortalSignupPolicy, soft_delete);
