//! Validator for PortalAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PortalAuditLog>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::PortalAuditLog;

/// Validator type alias for PortalAuditLog entities.
pub type PortalAuditLogValidator = EntityValidator<PortalAuditLog>;

/// Build a validator for PortalAuditLog with all schema-defined field rules.
pub fn portal_audit_log_validator() -> PortalAuditLogValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("actor", |e: &PortalAuditLog| e.actor.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
