//! Validator for PortalToken entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PortalToken>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PortalToken;

/// Validator type alias for PortalToken entities.
pub type PortalTokenValidator = EntityValidator<PortalToken>;

/// Build a validator for PortalToken with all schema-defined field rules.
pub fn portal_token_validator() -> PortalTokenValidator {
    EntityValidator::new()
        .rule(RequiredString::new("token_nonce", |e: &PortalToken| &e.token_nonce))
        .rule(OptionalNotBlank::new("revocation_reason", |e: &PortalToken| e.revocation_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
