//! Validator for PortalSignupPolicy entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PortalSignupPolicy>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::PortalSignupPolicy;

/// Validator type alias for PortalSignupPolicy entities.
pub type PortalSignupPolicyValidator = EntityValidator<PortalSignupPolicy>;

/// Build a validator for PortalSignupPolicy with all schema-defined field rules.
pub fn portal_signup_policy_validator() -> PortalSignupPolicyValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("note", |e: &PortalSignupPolicy| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
