//! Validator for PortalInvite entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PortalInvite>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PortalInvite;

/// Validator type alias for PortalInvite entities.
pub type PortalInviteValidator = EntityValidator<PortalInvite>;

/// Build a validator for PortalInvite with all schema-defined field rules.
pub fn portal_invite_validator() -> PortalInviteValidator {
    EntityValidator::new()
        .rule(RequiredString::new("recipient_email", |e: &PortalInvite| &e.recipient_email))
        .rule(RequiredString::new("token_nonce", |e: &PortalInvite| &e.token_nonce))
        .rule(OptionalNotBlank::new("revocation_reason", |e: &PortalInvite| e.revocation_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
