//! Validator for PortalUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PortalUser>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PortalUser;

/// Validator type alias for PortalUser entities.
pub type PortalUserValidator = EntityValidator<PortalUser>;

/// Build a validator for PortalUser with all schema-defined field rules.
pub fn portal_user_validator() -> PortalUserValidator {
    EntityValidator::new()
        .rule(RequiredString::new("email", |e: &PortalUser| &e.email))
        .rule(OptionalNotBlank::new("display_name", |e: &PortalUser| e.display_name.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &PortalUser| e.phone.as_deref()))
        .rule(OptionalNotBlank::new("street", |e: &PortalUser| e.street.as_deref()))
        .rule(OptionalNotBlank::new("street2", |e: &PortalUser| e.street2.as_deref()))
        .rule(OptionalNotBlank::new("city", |e: &PortalUser| e.city.as_deref()))
        .rule(OptionalNotBlank::new("state_id", |e: &PortalUser| e.state_id.as_deref()))
        .rule(OptionalNotBlank::new("country_id", |e: &PortalUser| e.country_id.as_deref()))
        .rule(OptionalNotBlank::new("zip", |e: &PortalUser| e.zip.as_deref()))
        .rule(OptionalNotBlank::new("vat", |e: &PortalUser| e.vat.as_deref()))
        .rule(OptionalNotBlank::new("company_name", |e: &PortalUser| e.company_name.as_deref()))
        .rule(OptionalNotBlank::new("revocation_reason", |e: &PortalUser| e.revocation_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
