//! PortalUser API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PortalUser CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PORTALUSER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PortalUser
pub struct PortalUserTestData;

impl TestDataGenerator for PortalUserTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "display_name": null,
            "status": "invited",
            "phone": null,
            "street": null,
            "street2": null,
            "city": null,
            "state_id": null,
            "country_id": null,
            "zip": null,
            "vat": null,
            "company_name": null,
            "sapiens_user_id": null,
            "revoked_at": now,
            "revocation_reason": null,
            "archived_at": now,
            "last_login_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "display_name": null,
            "status": "invited",
            "phone": null,
            "street": null,
            "street2": null,
            "city": null,
            "state_id": null,
            "country_id": null,
            "zip": null,
            "vat": null,
            "company_name": null,
            "sapiens_user_id": null,
            "revoked_at": now,
            "revocation_reason": null,
            "archived_at": now,
            "last_login_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PORTALUSER API TEST
// ============================================================================

/// PortalUser API test suite
pub struct PortalUserApiTest {
    inner: GenericCrudTest<PortalUserTestData>,
}

impl PortalUserApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/portal_users", "PortalUser");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PortalUserTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PortalUserApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_portal_user_crud() {
        let mut test = PortalUserApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PortalUser specific tests here
// <<< CUSTOM TESTS END >>>
