//! PortalToken API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PortalToken CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PORTALTOKEN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PortalToken
pub struct PortalTokenTestData;

impl TestDataGenerator for PortalTokenTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "user_id": Uuid::new_v4().to_string(),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "status": "active",
            "rotated_at": now,
            "rotated_to": null,
            "revoked_at": now,
            "revocation_reason": null,
            "last_used_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "user_id": Uuid::new_v4().to_string(),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "status": "active",
            "rotated_at": now,
            "rotated_to": null,
            "revoked_at": now,
            "revocation_reason": null,
            "last_used_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/portal_users", &super::portal_user_api_test::PortalUserTestData).await {
            deps.push(("user_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// PORTALTOKEN API TEST
// ============================================================================

/// PortalToken API test suite
pub struct PortalTokenApiTest {
    inner: GenericCrudTest<PortalTokenTestData>,
}

impl PortalTokenApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/portal_tokens", "PortalToken");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PortalTokenTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PortalTokenApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_portal_token_crud() {
        let mut test = PortalTokenApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PortalToken specific tests here
// <<< CUSTOM TESTS END >>>
