//! PortalInvite API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PortalInvite CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PORTALINVITE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PortalInvite
pub struct PortalInviteTestData;

impl TestDataGenerator for PortalInviteTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "recipient_email": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "status": "pending",
            "granted_by": null,
            "redeemed_by": null,
            "redeemed_at": now,
            "revoked_at": now,
            "revocation_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "recipient_email": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "status": "pending",
            "granted_by": null,
            "redeemed_by": null,
            "redeemed_at": now,
            "revoked_at": now,
            "revocation_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PORTALINVITE API TEST
// ============================================================================

/// PortalInvite API test suite
pub struct PortalInviteApiTest {
    inner: GenericCrudTest<PortalInviteTestData>,
}

impl PortalInviteApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/portal_invites", "PortalInvite");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PortalInviteTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PortalInviteApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_portal_invite_crud() {
        let mut test = PortalInviteApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PortalInvite specific tests here
// <<< CUSTOM TESTS END >>>
