//! Portal Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::PortalAuditLogService;
use crate::application::service::PortalInviteService;
use crate::application::service::PortalSignupPolicyService;
use crate::application::service::PortalTokenService;
use crate::application::service::PortalUserService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// PortalAuditLog service
    pub portal_audit_log_service: Arc<PortalAuditLogService>,
    /// PortalInvite service
    pub portal_invite_service: Arc<PortalInviteService>,
    /// PortalSignupPolicy service
    pub portal_signup_policy_service: Arc<PortalSignupPolicyService>,
    /// PortalToken service
    pub portal_token_service: Arc<PortalTokenService>,
    /// PortalUser service
    pub portal_user_service: Arc<PortalUserService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        portal_audit_log_service: Arc<PortalAuditLogService>,
        portal_invite_service: Arc<PortalInviteService>,
        portal_signup_policy_service: Arc<PortalSignupPolicyService>,
        portal_token_service: Arc<PortalTokenService>,
        portal_user_service: Arc<PortalUserService>
    ) -> Self {
        Self {
            portal_audit_log_service,
            portal_invite_service,
            portal_signup_policy_service,
            portal_token_service,
            portal_user_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PortalModule) -> Self {
        Self {
            portal_audit_log_service: module.portal_audit_log_service.clone(),
            portal_invite_service: module.portal_invite_service.clone(),
            portal_signup_policy_service: module.portal_signup_policy_service.clone(),
            portal_token_service: module.portal_token_service.clone(),
            portal_user_service: module.portal_user_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    portal_audit_log_service: Option<Arc<PortalAuditLogService>>,
    portal_invite_service: Option<Arc<PortalInviteService>>,
    portal_signup_policy_service: Option<Arc<PortalSignupPolicyService>>,
    portal_token_service: Option<Arc<PortalTokenService>>,
    portal_user_service: Option<Arc<PortalUserService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the PortalAuditLog service.
    pub fn with_portal_audit_log_service(mut self, service: Arc<PortalAuditLogService>) -> Self {
        self.portal_audit_log_service = Some(service);
        self
    }

    /// Set the PortalInvite service.
    pub fn with_portal_invite_service(mut self, service: Arc<PortalInviteService>) -> Self {
        self.portal_invite_service = Some(service);
        self
    }

    /// Set the PortalSignupPolicy service.
    pub fn with_portal_signup_policy_service(mut self, service: Arc<PortalSignupPolicyService>) -> Self {
        self.portal_signup_policy_service = Some(service);
        self
    }

    /// Set the PortalToken service.
    pub fn with_portal_token_service(mut self, service: Arc<PortalTokenService>) -> Self {
        self.portal_token_service = Some(service);
        self
    }

    /// Set the PortalUser service.
    pub fn with_portal_user_service(mut self, service: Arc<PortalUserService>) -> Self {
        self.portal_user_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            portal_audit_log_service: self.portal_audit_log_service.expect("portal_audit_log_service is required"),
            portal_invite_service: self.portal_invite_service.expect("portal_invite_service is required"),
            portal_signup_policy_service: self.portal_signup_policy_service.expect("portal_signup_policy_service is required"),
            portal_token_service: self.portal_token_service.expect("portal_token_service is required"),
            portal_user_service: self.portal_user_service.expect("portal_user_service is required"),
        }
    }
}
