//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    portal_audit_log_handler::create_portal_audit_log_read_routes,
    portal_invite_handler::create_portal_invite_read_routes,
    portal_signup_policy_handler::create_portal_signup_policy_read_routes,
    portal_token_handler::create_portal_token_read_routes,
    portal_user_handler::create_portal_user_read_routes,
};

use crate::application::service::{
    PortalAuditLogService,
    PortalInviteService,
    PortalSignupPolicyService,
    PortalTokenService,
    PortalUserService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub portal_audit_log: Arc<PortalAuditLogService>,
    pub portal_invite: Arc<PortalInviteService>,
    pub portal_signup_policy: Arc<PortalSignupPolicyService>,
    pub portal_token: Arc<PortalTokenService>,
    pub portal_user: Arc<PortalUserService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // PortalAuditLog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_portal_audit_log_read_routes(services.portal_audit_log))
        // PortalInvite routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_portal_invite_read_routes(services.portal_invite))
        // PortalSignupPolicy routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_portal_signup_policy_read_routes(services.portal_signup_policy))
        // PortalToken routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_portal_token_read_routes(services.portal_token))
        // PortalUser routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_portal_user_read_routes(services.portal_user))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn portal_audit_log_routes(service: Arc<PortalAuditLogService>) -> Router {
        create_portal_audit_log_routes(service)
    }

    pub fn portal_invite_routes(service: Arc<PortalInviteService>) -> Router {
        create_portal_invite_routes(service)
    }

    pub fn portal_signup_policy_routes(service: Arc<PortalSignupPolicyService>) -> Router {
        create_portal_signup_policy_routes(service)
    }

    pub fn portal_token_routes(service: Arc<PortalTokenService>) -> Router {
        create_portal_token_routes(service)
    }

    pub fn portal_user_routes(service: Arc<PortalUserService>) -> Router {
        create_portal_user_routes(service)
    }

}
