//! Public events for Portal module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// PORTALAUDITLOG EVENTS
// ============================================================================

/// Event published when a PortalAuditLog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogCreatedEvent {
    pub id: PortalAuditLogId,
    pub data: PortalAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalAuditLog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogUpdatedEvent {
    pub id: PortalAuditLogId,
    pub data: PortalAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalAuditLog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogDeletedEvent {
    pub id: PortalAuditLogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PORTALINVITE EVENTS
// ============================================================================

/// Event published when a PortalInvite is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteCreatedEvent {
    pub id: PortalInviteId,
    pub data: PortalInviteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalInvite is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteUpdatedEvent {
    pub id: PortalInviteId,
    pub data: PortalInviteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalInvite is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteDeletedEvent {
    pub id: PortalInviteId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PORTALSIGNUPPOLICY EVENTS
// ============================================================================

/// Event published when a PortalSignupPolicy is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicyCreatedEvent {
    pub id: PortalSignupPolicyId,
    pub data: PortalSignupPolicyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalSignupPolicy is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicyUpdatedEvent {
    pub id: PortalSignupPolicyId,
    pub data: PortalSignupPolicyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalSignupPolicy is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicyDeletedEvent {
    pub id: PortalSignupPolicyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PORTALTOKEN EVENTS
// ============================================================================

/// Event published when a PortalToken is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenCreatedEvent {
    pub id: PortalTokenId,
    pub data: PortalTokenDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalToken is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenUpdatedEvent {
    pub id: PortalTokenId,
    pub data: PortalTokenDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalToken is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenDeletedEvent {
    pub id: PortalTokenId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PORTALUSER EVENTS
// ============================================================================

/// Event published when a PortalUser is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserCreatedEvent {
    pub id: PortalUserId,
    pub data: PortalUserDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalUser is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserUpdatedEvent {
    pub id: PortalUserId,
    pub data: PortalUserDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PortalUser is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserDeletedEvent {
    pub id: PortalUserId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Portal module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PortalEvent {
    PortalAuditLogCreated(PortalAuditLogCreatedEvent),
    PortalAuditLogUpdated(PortalAuditLogUpdatedEvent),
    PortalAuditLogDeleted(PortalAuditLogDeletedEvent),
    PortalInviteCreated(PortalInviteCreatedEvent),
    PortalInviteUpdated(PortalInviteUpdatedEvent),
    PortalInviteDeleted(PortalInviteDeletedEvent),
    PortalSignupPolicyCreated(PortalSignupPolicyCreatedEvent),
    PortalSignupPolicyUpdated(PortalSignupPolicyUpdatedEvent),
    PortalSignupPolicyDeleted(PortalSignupPolicyDeletedEvent),
    PortalTokenCreated(PortalTokenCreatedEvent),
    PortalTokenUpdated(PortalTokenUpdatedEvent),
    PortalTokenDeleted(PortalTokenDeletedEvent),
    PortalUserCreated(PortalUserCreatedEvent),
    PortalUserUpdated(PortalUserUpdatedEvent),
    PortalUserDeleted(PortalUserDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PortalEventMetadata {
    fn default() -> Self {
        Self {
            module: "portal",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
