//! Portal Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Portal exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use portal::exports::{PortalAuditLogDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `PortalAuditLogDto` - Data transfer object for PortalAuditLog
/// - `PortalAuditLogSummary` - Summary view of PortalAuditLog
/// - `PortalAuditLogId` - Type-safe ID wrapper
/// - `PortalInviteDto` - Data transfer object for PortalInvite
/// - `PortalInviteSummary` - Summary view of PortalInvite
/// - `PortalInviteId` - Type-safe ID wrapper
/// - `PortalSignupPolicyDto` - Data transfer object for PortalSignupPolicy
/// - `PortalSignupPolicySummary` - Summary view of PortalSignupPolicy
/// - `PortalSignupPolicyId` - Type-safe ID wrapper
/// - `PortalTokenDto` - Data transfer object for PortalToken
/// - `PortalTokenSummary` - Summary view of PortalToken
/// - `PortalTokenId` - Type-safe ID wrapper
/// - `PortalUserDto` - Data transfer object for PortalUser
/// - `PortalUserSummary` - Summary view of PortalUser
/// - `PortalUserId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `PortalAuditLogCreatedEvent` - Published when PortalAuditLog is created
/// - `PortalAuditLogUpdatedEvent` - Published when PortalAuditLog is updated
/// - `PortalAuditLogDeletedEvent` - Published when PortalAuditLog is deleted
/// - `PortalInviteCreatedEvent` - Published when PortalInvite is created
/// - `PortalInviteUpdatedEvent` - Published when PortalInvite is updated
/// - `PortalInviteDeletedEvent` - Published when PortalInvite is deleted
/// - `PortalSignupPolicyCreatedEvent` - Published when PortalSignupPolicy is created
/// - `PortalSignupPolicyUpdatedEvent` - Published when PortalSignupPolicy is updated
/// - `PortalSignupPolicyDeletedEvent` - Published when PortalSignupPolicy is deleted
/// - `PortalTokenCreatedEvent` - Published when PortalToken is created
/// - `PortalTokenUpdatedEvent` - Published when PortalToken is updated
/// - `PortalTokenDeletedEvent` - Published when PortalToken is deleted
/// - `PortalUserCreatedEvent` - Published when PortalUser is created
/// - `PortalUserUpdatedEvent` - Published when PortalUser is updated
/// - `PortalUserDeletedEvent` - Published when PortalUser is deleted
pub struct ExportSummary;
