//! Public types for Portal module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// PORTALAUDITLOG TYPES
// ============================================================================

/// Type-safe ID for PortalAuditLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortalAuditLogId(pub Uuid);

impl PortalAuditLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PortalAuditLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PortalAuditLogId> for Uuid {
    fn from(id: PortalAuditLogId) -> Self {
        id.0
    }
}

/// Data transfer object for PortalAuditLog
///
/// This is the public representation of PortalAuditLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogDto {
    pub id: PortalAuditLogId,
    pub event: PortalAuditEvent,
    pub portal_user_id: Option<Uuid>,
    pub invite_id: Option<Uuid>,
    pub token_id: Option<Uuid>,
    pub actor: Option<String>,
    pub detail: Option<serde_json::Value>,
    pub occurred_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of PortalAuditLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogSummary {
    pub id: PortalAuditLogId,
}

/// Reference to PortalAuditLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalAuditLogRef {
    pub id: PortalAuditLogId,
}

// ============================================================================
// PORTALINVITE TYPES
// ============================================================================

/// Type-safe ID for PortalInvite
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortalInviteId(pub Uuid);

impl PortalInviteId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PortalInviteId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PortalInviteId> for Uuid {
    fn from(id: PortalInviteId) -> Self {
        id.0
    }
}

/// Data transfer object for PortalInvite
///
/// This is the public representation of PortalInvite for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteDto {
    pub id: PortalInviteId,
    pub recipient_email: String,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalInviteStatus,
    pub granted_by: Option<Uuid>,
    pub redeemed_by: Option<Uuid>,
    pub redeemed_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of PortalInvite for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteSummary {
    pub id: PortalInviteId,
    pub status: PortalInviteStatus,
}

/// Reference to PortalInvite for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalInviteRef {
    pub id: PortalInviteId,
}

// ============================================================================
// PORTALSIGNUPPOLICY TYPES
// ============================================================================

/// Type-safe ID for PortalSignupPolicy
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortalSignupPolicyId(pub Uuid);

impl PortalSignupPolicyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PortalSignupPolicyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PortalSignupPolicyId> for Uuid {
    fn from(id: PortalSignupPolicyId) -> Self {
        id.0
    }
}

/// Data transfer object for PortalSignupPolicy
///
/// This is the public representation of PortalSignupPolicy for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicyDto {
    pub id: PortalSignupPolicyId,
    pub enabled: bool,
    pub note: Option<String>,
    pub updated_by: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of PortalSignupPolicy for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicySummary {
    pub id: PortalSignupPolicyId,
}

/// Reference to PortalSignupPolicy for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalSignupPolicyRef {
    pub id: PortalSignupPolicyId,
}

// ============================================================================
// PORTALTOKEN TYPES
// ============================================================================

/// Type-safe ID for PortalToken
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortalTokenId(pub Uuid);

impl PortalTokenId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PortalTokenId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PortalTokenId> for Uuid {
    fn from(id: PortalTokenId) -> Self {
        id.0
    }
}

/// Data transfer object for PortalToken
///
/// This is the public representation of PortalToken for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenDto {
    pub id: PortalTokenId,
    pub user_id: Uuid,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub status: PortalTokenStatus,
    pub rotated_at: Option<DateTime<Utc>>,
    pub rotated_to: Option<Uuid>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of PortalToken for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenSummary {
    pub id: PortalTokenId,
    pub status: PortalTokenStatus,
}

/// Reference to PortalToken for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalTokenRef {
    pub id: PortalTokenId,
}

// ============================================================================
// PORTALUSER TYPES
// ============================================================================

/// Type-safe ID for PortalUser
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortalUserId(pub Uuid);

impl PortalUserId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PortalUserId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PortalUserId> for Uuid {
    fn from(id: PortalUserId) -> Self {
        id.0
    }
}

/// Data transfer object for PortalUser
///
/// This is the public representation of PortalUser for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserDto {
    pub id: PortalUserId,
    pub email: String,
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    pub phone: Option<String>,
    pub street: Option<String>,
    pub street2: Option<String>,
    pub city: Option<String>,
    pub state_id: Option<String>,
    pub country_id: Option<String>,
    pub zip: Option<String>,
    pub vat: Option<String>,
    pub company_name: Option<String>,
    pub sapiens_user_id: Option<Uuid>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revocation_reason: Option<String>,
    pub archived_at: Option<DateTime<Utc>>,
    pub last_login_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of PortalUser for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserSummary {
    pub id: PortalUserId,
    pub email: String,
    pub display_name: Option<String>,
    pub status: PortalUserStatus,
    pub company_name: Option<String>,
}

/// Reference to PortalUser for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortalUserRef {
    pub id: PortalUserId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
