//! Portal Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::PortalAuditLogService;
pub use application::service::PortalInviteService;
pub use application::service::PortalSignupPolicyService;
pub use application::service::PortalTokenService;
pub use application::service::PortalUserService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Portal module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let portal = PortalModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = portal.all_crud_routes();
/// ```
pub struct PortalModule {
    pub(crate) portal_audit_log_service: Arc<PortalAuditLogService>,
    pub(crate) portal_invite_service: Arc<PortalInviteService>,
    pub(crate) portal_signup_policy_service: Arc<PortalSignupPolicyService>,
    pub(crate) portal_token_service: Arc<PortalTokenService>,
    pub(crate) portal_user_service: Arc<PortalUserService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl PortalModule {
    /// Create a new module builder
    pub fn builder() -> PortalModuleBuilder {
        PortalModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_portal_audit_log_read_routes,
            create_portal_invite_read_routes,
            create_portal_signup_policy_read_routes,
            create_portal_token_read_routes,
            create_portal_user_read_routes,
        };

        Router::new()
            .merge(create_portal_audit_log_read_routes(self.portal_audit_log_service.clone()))
            .merge(create_portal_invite_read_routes(self.portal_invite_service.clone()))
            .merge(create_portal_signup_policy_read_routes(self.portal_signup_policy_service.clone()))
            .merge(create_portal_token_read_routes(self.portal_token_service.clone()))
            .merge(create_portal_user_read_routes(self.portal_user_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_portal_audit_log_read_routes,
            create_portal_invite_read_routes,
            create_portal_signup_policy_read_routes,
            create_portal_token_read_routes,
            create_portal_user_read_routes,
        };

        Router::new()
            .merge(create_portal_audit_log_read_routes(self.portal_audit_log_service.clone()))
            .merge(create_portal_invite_read_routes(self.portal_invite_service.clone()))
            .merge(create_portal_signup_policy_read_routes(self.portal_signup_policy_service.clone()))
            .merge(create_portal_token_read_routes(self.portal_token_service.clone()))
            .merge(create_portal_user_read_routes(self.portal_user_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for PortalModule
pub struct PortalModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PortalModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PortalModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // PortalAuditLog service
        let portal_audit_log_repository = Arc::new(PortalAuditLogRepository::new(db_pool.clone()));
        let portal_audit_log_service = Arc::new(PortalAuditLogService::with_repository(portal_audit_log_repository.clone()));

        // PortalInvite service
        let portal_invite_repository = Arc::new(PortalInviteRepository::new(db_pool.clone()));
        let portal_invite_service = Arc::new(PortalInviteService::with_repository(portal_invite_repository.clone()));

        // PortalSignupPolicy service
        let portal_signup_policy_repository = Arc::new(PortalSignupPolicyRepository::new(db_pool.clone()));
        let portal_signup_policy_service = Arc::new(PortalSignupPolicyService::with_repository(portal_signup_policy_repository.clone()));

        // PortalToken service
        let portal_token_repository = Arc::new(PortalTokenRepository::new(db_pool.clone()));
        let portal_token_service = Arc::new(PortalTokenService::with_repository(portal_token_repository.clone()));

        // PortalUser service
        let portal_user_repository = Arc::new(PortalUserRepository::new(db_pool.clone()));
        let portal_user_service = Arc::new(PortalUserService::with_repository(portal_user_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(PortalModule {
            portal_audit_log_service,
            portal_invite_service,
            portal_signup_policy_service,
            portal_token_service,
            portal_user_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PortalModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
